
spring:
  datasource:
   # url: jdbc:h2:tcp://localhost/~/blog
    url : jdbc:h2:mem:blog
    username: sa
    password:
    driver-class-name: org.h2.Driver
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  jpa:
    hibernate:
      ddl-auto: create # ???? ??? drop? ???
    properties:
      hibernate:
        show_sql: false
        format_sql: false
        default_batch_fetch_size: 1000 # multibagfetchException 해결

logging:
  level:
    org.hibernate.sql: debug

file:
  dir: /Users/minjiwon/Desktop/file-upload/

profile:
  dir: /Users/minjiwon/Desktop/profile/

banner:
  dir: /Users/minjiwon/Desktop/banner/