name: Java CI with Gradle

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'zulu'
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew build -x test
      - name: Docker Login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
      - name: Docker Build
        run:  docker build -t blog-spring-cicd .
          docker tag spring-cicd jiwon27/blog-spring-cicd:${GITHUB_SHA::7}
          docker push jiwon27/blog-spring-cicd:${GITHUB_SHA::7}
      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ec2-43-202-63-17.ap-northeast-2.compute.amazonaws.com
          username: ubuntu
          key: ${{ secrets.KEY }}
          envs: GITHUB_SHA
          script: |
            docker pull jiwon27/blog-spring-cicd:${GITHUB_SHA::7}
            docker tag jiwon27/blog-spring-cicd:${GITHUB_SHA::7} blog-spring-cicd
            docker stop server
            docker rm -f server
            docker run -d --name server -p 8080:8080 blog-spring-cicd